branch-defaults:
  default:
    environment: django-bharatmenuapp
    group_suffix: null
environment-defaults:
  django-bharatmenuapp:
    branch: null
    repository: null
global:
  application_name: django-backend-bharatmenu
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
