# Generated by Django 4.1.1 on 2022-11-12 19:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('RankingFactor', models.IntegerField(default=1)),
                ('CategoryImage', models.ImageField(blank=True,
                 default='category_default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
                ('RankingFactor', models.IntegerField(default=1)),
                ('Pincode', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemsNumber', models.PositiveIntegerField()),
                ('UserName', models.CharField(max_length=25)),
                ('UserPhone', models.PositiveBigIntegerField(default=0)),
                ('OrderDateTime', models.DateTimeField(auto_now_add=True)),
                ('TableNumber', models.PositiveIntegerField()),
                ('TotalPrice', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileId', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.PositiveBigIntegerField(default=0)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Note', models.CharField(default='', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantId', models.AutoField(
                    primary_key=True, serialize=False)),
                ('ShopName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Rating', models.IntegerField(default=5, help_text='Value 1 to 10', validators=[
                 django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('DateOfJoining', models.DateField(default=datetime.date.today)),
                ('RankingFactor', models.IntegerField(default=1)),
                ('RestaurantImage', models.ImageField(blank=True,
                 default='restaurant_default.png', upload_to='')),
                ('PhotoFileName', models.CharField(blank=True, max_length=100)),
                ('CityName', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('OrderItemId', models.AutoField(
                    primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.PositiveBigIntegerField()),
                ('OrderId', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='RestaurantId',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.restaurant'),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('MerchantId', models.AutoField(primary_key=True, serialize=False)),
                ('ShopName', models.CharField(max_length=150)),
                ('fullName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('phoneNumber', models.PositiveBigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('userId', models.PositiveBigIntegerField(default=0)),
                ('gst', models.PositiveBigIntegerField(default=0)),
                ('CityName', models.CharField(default='', max_length=100)),
                ('Pincode', models.PositiveIntegerField(default=0)),
                ('ProfileId', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.profile')),
                ('RestaurantId', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.PositiveIntegerField()),
                ('Rating', models.IntegerField(default=5, help_text='Value 1 to 10', validators=[
                 django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('ItemPhotoName', models.CharField(blank=True, max_length=100)),
                ('RankingFactor', models.IntegerField(default=1)),
                ('ItemImage', models.ImageField(blank=True,
                 default='menuitem_default.png', upload_to='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[
                 ('1', 'VEG'), ('2', 'NONVEG')], default='1', max_length=2)),
                ('Combo', models.BooleanField(default=False)),
                ('Popular', models.BooleanField(default=False)),
                ('MustTry', models.BooleanField(default=False)),
                ('Available', models.BooleanField(default=False)),
                ('BestSeller', models.BooleanField(default=False)),
                ('Description', models.CharField(default='', max_length=25)),
                ('TodaysSpecial', models.BooleanField(default=False)),
                ('CategoryName', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.category')),
                ('RestaurantName', models.ForeignKey(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='RestaurantName',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.restaurant'),
        ),
    ]
