# Generated by Django 4.1.1 on 2023-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='CityName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
