# Generated by Django 4.1.1 on 2023-03-12 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bharatMenuApp', '0006_alter_merchant_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
