# Generated by Django 4.1.1 on 2023-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0007_alter_merchant_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
