# Generated by Django 4.1.1 on 2023-11-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0013_alter_query_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Image',
            field=models.ImageField(blank=True, default='happy.png', upload_to=''),
        ),
    ]
