# Generated by Django 4.1.1 on 2023-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0015_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='id',
        ),
        migrations.AddField(
            model_name='reminder',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
