# Generated by Django 4.1.1 on 2023-12-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0016_remove_reminder_id_reminder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
