# Generated by Django 4.1.1 on 2023-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0018_rename_id_reminder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
