# Generated by Django 4.1.1 on 2023-12-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0019_alter_reminder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
