# Generated by Django 4.1.1 on 2024-01-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0021_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='call_sid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user_response',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profileId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='taskId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.task'),
        ),
    ]
