# Generated by Django 4.1.1 on 2024-01-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0022_reminder_call_sid_reminder_user_response_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='taskId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.task'),
        ),
    ]
