# Generated by Django 4.1.1 on 2024-01-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0024_alter_reminder_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='taskId',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bharatMenuApp.task'),
        ),
    ]
