# Generated by Django 4.1.1 on 2024-01-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0025_alter_reminder_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='taskId',
        ),
    ]
