# Generated by Django 4.1.1 on 2024-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharatMenuApp', '0027_reminder_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SubscriptionStatus',
            field=models.CharField(choices=[('1', 'BASIC'), ('2', 'PLUS'), ('3', 'PRO')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='taskName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
